// Generated by LiveScript 1.2.0
(function(){
  var P, runtime, interpreter;
  P = require('./primitives');
  runtime = require('./runtime');
  interpreter = function(ground, seq, current){
    var i$, ref$, len$, msg;
    current == null && (current = ground);
    for (i$ = 0, len$ = (ref$ = seq.msgs).length; i$ < len$; ++i$) {
      msg = ref$[i$];
      if (msg.id instanceof P.Symbol && msg.id.val === '.') {
        current = ground;
      } else {
        current = new runtime.Call(ground, current, msg).send();
      }
    }
    return current;
  };
  module.exports = interpreter;
}).call(this);
