// Generated by LiveScript 1.2.0
(function(){
  var A, shuffleAssignment;
  A = require('./ast');
  shuffleAssignment = function(seq){
    var newSeq, stack, current, i$, ref$, len$, msg, newMsg;
    newSeq = [];
    stack = [newSeq];
    current = function(){
      return stack[stack.length - 1];
    };
    for (i$ = 0, len$ = (ref$ = seq.msgs).length; i$ < len$; ++i$) {
      msg = ref$[i$];
      newMsg = A.msg(msg.id, []);
      if (msg.id.data === '=' && msg.args.length === 0) {
        if (current().length == null) {
          throw new Error('Assignment cannot be the first message');
        }
        newMsg.args[0] = current().pop();
        newMsg.args[1] = A.msgSeq();
        current().push(newMsg);
        stack.push(newMsg.args[1].msgs);
      } else if (msg.id.data === '.' && msg.args.length === 0) {
        stack.pop();
      } else {
        newMsg.args = msg.args.map(shuffleAssignment);
        current().push(newMsg);
      }
    }
    return A.msgSeq(newSeq);
  };
  exports.assignment = shuffleAssignment;
}).call(this);
