// Generated by LiveScript 1.2.0
(function(){
  var Parser, runtime, interpreter, transformer, util, p, transformed;
  Parser = require('./parser');
  runtime = require('./runtime');
  interpreter = require('./interpreter');
  transformer = require('./transformer');
  util = require('util');
  p = new Parser;
  p.add('/#print("hi")\nprint(:\'\\\'\')\nprint(foo\'hi\')#/\nprint(hello\\ world)');
  p.parse();
  console.log(p.seq);
  console.log(p.seq.toCode());
  transformed = transformer(p.seq, [transformer.str()]);
  console.log(transformed);
  console.log(transformed.toCode());
}).call(this);
