// Generated by LiveScript 1.2.0
(function(){
  var U, UserData;
  U = exports;
  U.UserData = UserData = (function(){
    UserData.displayName = 'UserData';
    var prototype = UserData.prototype, constructor = UserData;
    function UserData(){}
    return UserData;
  }());
}).call(this);
